export const sample_foods = [
  {
    id: "1",
    name: "Chicken Kottu ",
    cookTime: "10-20",
    price: 1000,
    favorite: false,
    origins: ["Sri lankan"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["SlowFood", "Kottu", "Lunch"],
  },
  {
    id: "2",
    name: "Lumprise",
    price: 1500,
    cookTime: "20-30",
    favorite: true,
    origins: ["Sri lankan"],
    stars: 5,
    imageUrl: "food-2.jpg",
    tags: ["SlowFood", "Lunch"],
  },
  {
    id: "3",
    name: "Briyani",
    price: 2000,
    cookTime: "10-15",
    favorite: false,
    origins: ["indian","Sri Lankan"],
    stars: 3.5,
    imageUrl: "food-3.jpg",
    tags: ["SlowFood", "Briyani","indian"],
  },
  {
    id: "4",
    name: "Dosai",
    price: 500,
    cookTime: "15-20",
    favorite: true,
    origins: ["indian"],
    stars: 3,
    imageUrl: "food-4.jpg",
    tags: ["FastFood", "Breakfast","indian"],
  },
  {
    id: "5",
    name: "String Hopers",
    price: 1000,
    cookTime: "40-50",
    favorite: false,
    origins: ["india", "asia"],
    stars: 3.5,
    imageUrl: "food-5.jpg",
    tags: ["SlowFood", "Breakfast"],
  },
  {
    id: "6",
    name: "Fried Rice",
    price: 2500,
    cookTime: "40-50",
    favorite: false,
    origins: ["Sri Lankan"],
    stars: 4.0,
    imageUrl: "food-6.jpg",
    tags: ["FastFood", "Lunch"],
  },
];

export const sample_tags = [
  { name: "All", count: 6 },
  { name: "Breakfast", count: 4 },
  { name: "Dinner", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "FastFood", count: 2 },
  { name: "Rice", count: 1 },
  { name: "Kottu", count: 1 },
  { name: "indian", count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: "user",
    email: "yasi@user.com",
    password: "12345",
    address: "colombo",
    isAdmin: false,
  },
  {
    id: 2,
    name: "admin",
    email: "admin@admin.com",
    password: "12345",
    address: "kandy",
    isAdmin: true,
  },
];
